389,100
390,"test.tm1filetools.static_view_with_named_title_subset"
370,0
361,1
362,1
363,0
364,0
365,
366,
367,0
376,0
375,b:0.#########G|0|
374,1
7,}TimeIntervals
6,LATEST
360,1
7,}StatsByProcess
270,8
Current State
Completion Status
Client Name
Last Start Time
Last End Time
Last Duration
Next Activation Time
Current Process
274,
275,
281,0
282,
371,1
7,}Processes
270,121
cube.fx_rates.load
dimension.version.add
dimension.version.set_current_planning
new_process
new process
process.logging.end
process_logging.start
test.tm1filetools.empty_process
test.tm1filetools.epilog_only_process
test.tm1filetools.prolog_only_process
}bedrock.chore.execution.check
}bedrock.cube.clone
}bedrock.cube.create
}bedrock.cube.data.clear
}bedrock.cube.data.copy
}bedrock.cube.data.copy.intercube
}bedrock.cube.data.export
}bedrock.cube.data.import
}bedrock.cube.data.save
}bedrock.cube.delete
}bedrock.cube.dimension.add
}bedrock.cube.dimension.delete
}bedrock.cube.dimension.replace
}bedrock.cube.rule.manage
}bedrock.cube.rule.processfeeders
}bedrock.cube.view.create
}bedrock.cube.view.create.bymdx
}bedrock.cube.view.delete
}bedrock.cube.view.publish
}bedrock.cube.viewandsubsets.create
}bedrock.cube.viewandsubsets.delete
}bedrock.dim.attr.create
}bedrock.dim.attr.delete
}bedrock.dim.attr.importfromfile
}bedrock.dim.attr.swapalias
}bedrock.dim.clone
}bedrock.dim.delete
}bedrock.hier.clone
}bedrock.hier.consol.delete
}bedrock.hier.consol.flat.create
}bedrock.hier.create
}bedrock.hier.create.fromattribute
}bedrock.hier.create.fromrollup
}bedrock.hier.create.fromrollup.aliasswap
}bedrock.hier.create.fromsubset
}bedrock.hier.delete
}bedrock.hier.element.create
}bedrock.hier.element.delete
}bedrock.hier.element.move
}bedrock.hier.elements.validate
}bedrock.hier.emptyconsols.delete
}bedrock.hier.export
}bedrock.hier.export.script
}bedrock.hier.import
}bedrock.hier.leaves.orphan.check
}bedrock.hier.leaves.sync
}bedrock.hier.sub.clone
}bedrock.hier.sub.create
}bedrock.hier.sub.create.all
}bedrock.hier.sub.create.attribute.all
}bedrock.hier.sub.create.attribute.leaf
}bedrock.hier.sub.create.byelement
}bedrock.hier.sub.create.bylevel
}bedrock.hier.sub.create.bymdx
}bedrock.hier.sub.create.consolidation.all
}bedrock.hier.sub.create.consolidation.leaf
}bedrock.hier.sub.create.leaf
}bedrock.hier.sub.create.orphans
}bedrock.hier.sub.create.toplevelhierarchy
}bedrock.hier.sub.delete
}bedrock.hier.sub.exclude
}bedrock.hier.sub.exporttofile
}bedrock.hier.unwind
}bedrock.process.template
}bedrock.security.client.clone
}bedrock.security.client.create
}bedrock.security.client.delete
}bedrock.security.client.group.assign
}bedrock.security.client.password.reset
}bedrock.security.cube.cellsecurity.create
}bedrock.security.cube.cellsecurity.destroy
}bedrock.security.evaluate.mdx
}bedrock.security.evaluate.mdx.private
}bedrock.security.group.create
}bedrock.security.group.delete
}bedrock.security.object.assign
}bedrock.security.refresh
}bedrock.server.deleteallpersistentfeeders
}bedrock.server.dir.backup
}bedrock.server.dir.listcontents
}bedrock.server.encrypt.directory
}bedrock.server.encrypt.file
}bedrock.server.executecommand
}bedrock.server.localize
}bedrock.server.logfile.delete
}bedrock.server.savedataall
}bedrock.server.util.string.validate
}bedrock.server.wait
}bedrock.server.writetomessagelog
}Bedrock.v3.Cube.ViewAndSubsets.Delete
}Bedrock.v3.Dim.Element.Component.Delete
}Bedrock.v3.Dim.EmptyConsols.Delete
}bedrock.v3.dim.hierarchy.create.fromattribute
}Bedrock.v3.Dim.Hierarchy.Unwind.Consolidation
}internal.cube.fx_rates.create
}internal.cube.process_logging.create
}internal.dimension.company.create
}internal.dimension.currency_local.create
}internal.dimension.currency_reporting.create
}internal.dimension.line_item.create
}internal.dimension.measures_expense_planning.create
}internal.dimension.measures_fx_rates.create
}internal.dimension.measures_process_logging.create
}internal.dimension.period.create
}internal.dimension.publication.create
}internal.dimension.scenario.create
}internal.dimension.version.create
}internal.dimension.year.create
}internal.model.create
}internal.subset.all_n_elements.create
}internal.subset.non_control.create
274,
275,
281,0
282,
373,1
1,LATEST
372,0
372,00
384,0
385,0
377,4
1139
577
1932
1108
378,0
382,255
379,3
0
0
0
11,20221109123544
381,0
32,6
null\n
